### ISSUE TITLE
Tiago robot self-rotate in gazebo

### ISSUE THREAD

**Issue by nicehiro** [pal-robotics/tiago_robot#23] opened 2023-06-26 12:17 UTC
I'm encountering an issue recently that the tiago robot rotate by itself slightly in gazebo simulation.

Reproducing process:
- start simulation, and rotate tiago by a certain degree, and then stop tiago movement

Then tiago start self-rotating backwards slightly.

There's some same issues can be found here (one answer are using tiago too):
- https://answers.ros.org/question/310008/turtlebot-and-other-objects-unintentionally-moving-by-itself-in-gazebo/
- https://answers.ros.org/question/313899/banana-rotates-by-itself-in-gazebo-i-dont-know-why/
- https://answers.gazebosim.org/question/21944/banana-rotates-by-itself-in-gazebo-i-dont-know-why/

I've tried all the answers above, but still couldn't solve the issue.

**Comment by saikishor** [comment] 2023-06-26 14:15
Hello @nicehiro,

We will try to take a look at our end and get back to you!

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by nicehiro** [comment] 2023-06-28 05:39
Hi, @saikishor,

Sorry to bother you. Did you find any solutions?

I tried to open a ticket in PAL support center but it seems that the website is temporarily unavailable.

I also send emails to PAL but got no response.

**Comment by thomaspeyrucain** [comment] 2023-06-28 08:28
Hello @nicehiro,

Thank you for contacting us,

I could not reproduce your issue 
How are you launching the rotation process? Through navigation or key_teleop?
Which gazebo and ROS versions are you using?
How slight is the movement? Could you maybe share a video

Best regards,
PAL Robotics Team

**Comment by nicehiro** [comment] 2023-06-28 12:15
Hi, @thomaspeyrucain,

Thanks for your help.

I'm using ros noetic and the version of gazebo is `11.10.2`.

Here's the code I used to reproduce the error:

```
    vel_pub = rospy.Publisher(
        "/mobile_base_controller/cmd_vel", Twist, queue_size=10
    )

    # rotate
    for i in range(5):
        vel_cmd = Twist()
        vel_cmd.angular.z = 1
        vel_pub.publish(vel_cmd)
        rospy.sleep(1)

    # stop the robot
    vel_cmd = Twist()
    vel_pub.publish(vel_cmd)
```

Here's the [video](https://drive.google.com/file/d/1TFMuIrvPDqAPilpH6ZditG3wLiebqP6q/view?usp=sharing) running above code. As I have observed, the rotate speed is about 0.002 radians per 10 second.

**Comment by saikishor** [comment] 2023-06-28 14:54
Hello @nicehiro,

Thank you for sharing the information to reproduce it. As for us, the rotation drift (0.0002 rad/sec - 0.012 deg/sec) you are reporting is negligible to us, and this can be from the simulation artifacts or from [the PIDs of the joints](https://github.com/pal-robotics/tiago_simulation/blob/kinetic-devel/tiago_controller_configuration_gazebo/config/pids.yaml) or [the parameters of the wheels in gazebo](https://github.com/pal-robotics/pmb2_robot/blob/kinetic-devel/pmb2_description/urdf/wheels/wheel.gazebo.xacro#L14-L33). This is something negligible in usual simulation cases, for this reason, we will be going ahead and closing the issue. You can tweak the parameters that we linked above to reach the performance you are aiming for. 

Thank you for your cooperation, 

Best Regards,
PAL Robotics Team.

**Closed as completed by saikishor** 2023-06-28 14:54 UTC
